{{- if .Name }}
name: {{ .Name }}
{{- end }}
{{- if .Version }}
version: {{ .Version }}
{{- end }}
email: {{ .Custom.Email }}
staging: {{ .Custom.Staging }}
{{- if .Environment }}
environment:
  {{- range $key, $env := .Environment }}
  {{ $key }}: {{ $env }}
  {{- end }}
{{- end }}
