{{- $hostPrefix := .Custom.HostPrefix }}
name: {{ .Name }}
image: {{ .Image }}
tag: {{ .Version }}
{{- if .Custom.Ingress }}
ingress_map:
{{ if isSlice .Custom.Ingress -}}
{{ range $_, $ingress := .Custom.Ingress -}}
{{ if isSlice $ingress.Paths -}}
{{ range $_, $path := $ingress.Paths -}}
- path: {{ $path.Path }}
  strip: {{ $path.Strip }}
  {{ if isSlice $path.Hosts -}}
  hosts:
  {{ range $_, $host := $path.Hosts -}}
  - "{{ $hostPrefix }}{{ $host }}"
  {{ end -}}
  {{ end -}}
  namespace: {{ $ingress.Namespace }}
  upstream: {{ $ingress.ServiceName }}
  port: {{ $ingress.Port }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
{{- end }}
{{- if .Environment }}
environment:
  {{- range $key, $env := .Environment }}
  {{ $key }}: {{ $env }}
  {{- end }}
{{- end }}
