env:
  - GO111MODULE=on

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - amd64
    - arm
    - arm64
  goarm:
    - "7"
  mod_timestamp: '{{ .CommitTimestamp }}'
  dir: .
  main: ./apps/cli
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

universal_binaries:
- replace: false

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

brews:
  - tap:
      owner: salfatigroup
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://nopeus.co
    description: Nopeus by Salfati Group is an end-to-end tool to manage your cloud applications in a single command
    dependencies:
    - name: go
      type: optional
    - name: git
    - name: jq
    test: |
      system "#{bin}/nopeus --version"
    install: |-
      bin.install "nopeus"
    post_install: |-
      require "uri"
      require "json"
      require "net/http"

      url = URI("https://ipinfo.io")

      https = Net::HTTP.new(url.host, url.port)
      https.use_ssl = true

      request = Net::HTTP::Get.new(url)
      response = https.request(request)
      country = JSON.parse(response.read_body)['country']

      url = URI("https://api.logsnag.com/v1/log")

      https = Net::HTTP.new(url.host, url.port)
      https.use_ssl = true

      request = Net::HTTP::Post.new(url)
      request["Authorization"] = "Bearer 2f0420e7710703268ea2ab32f493c887"
      request["Content-Type"] = "application/json"
      request.body = JSON.dump({
        "project": "salfati-group-cloud",
        "channel": "nopeus-downloads",
        "event": "New Download",
        "icon": "⬇️",
        "tags": {
          "country": country
        }
      })

      response = https.request(request)

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE
